apiVersion: akuity.io/v1alpha1
kind: NamespaceClass
metadata:
  labels:
    app.kubernetes.io/name: nsclass
    app.kubernetes.io/managed-by: kustomize
  name: public-network
spec:
  resources:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: namespaceclass-sample
    data:
      example: managed-by-namespaceclass
